= Getting Started

If you have never logged in to the https://dashboard.gacyberrange.org[Georgia Cyber Range],
you probably need to register for an account.

[#registration]
== Registration

During the beta period (which runs until 31 December 2019),
please contact {{ fixme }} for information on how to register for an account.

Pricing information is still to be determined,
but low/no cost compute/storage/bandwidth is available to noteworthy efforts that further the cause of cybersecurity for the world at large.
For more information about this opportunity, please contact {{ fixme }}.

With a Georgia Cyber Range account, you get:

* Global access to the xref:what-is-the-georgia-cyber-range.adoc[Georgia Cyber Range]
* Access to your own GCR project with reserved resources
* The ability to gain access to shared projects for collaboration on special endeavors
* The ability to easily share resources with other organizations and individuals using the Georgia Cyber Range

For more information on maximizing the impact of your Georgia Cyber Range account,
see xref:gcr-guide.adoc[the Georgia Cyber Range User Guide]

[#logging-in]
== Logging in

Once you have a confirmed Georgia Cyber Range Account,
head to https://dashboard.gacyberrange.org and log in with the information provided.


