= Contributing

[#introduction]
== Introduction

This contribution guide will lay out how to do common tasks like report issues,
update code,
and submit requests to merge your changes back into the master branch of the https://github.com/GeorgiaCyber/kinetic[kinetic framework].

If you have never used Git or feel a bit rusty,
please spend soem time reading the https://www.atlassian.com/git/tutorials[Atlassian Git Guru Tutorials].

If you have not used Git in a professional environment (i.e. only for personal side projects), the following resources
are worth reading:

* https://jameschambers.co/writing/git-team-workflow-cheatsheet/[Git Team Workflow Cheatsheet]
* https://chris.beams.io/posts/git-commit/[How to Write a Git Commit Message]
* https://randyfay.com/content/rebase-workflow-git[A Rebase Workflow for Git]

If you prefer a more hands-on experience learning git, there is an interactive git tutorial at:

* https://learngitbranching.js.org/[Learn Git Branching]

All Georgia Cyber Center repositories (include kinetic),
unless explicitly specified otherwise,
will observe the https://guides.github.com/introduction/flow/[Github Flow]

[#submitting-issues]
== Submitting Issues

A core component of the feature branch workflow is to use a different branch for each individual feature or issue.
This implies that every branch should be mapped to an issue.

For example,
if you want to add an OpenStack project to the kinetic framework that is currently unsupported (e.g. https://docs.openstack.org/barbican/latest/[barbican]),
create a new issue (specifically, a https://github.com/GeorgiaCyber/kinetic/issues/new/choose[feature request] using the issue template) entitled
```[FEATURE] Add barbican to kinetic framework```
Titles should be specific and begin with the action taken (create, update, delete, etc.).

The body of the issue should reference any code,
logs,
or thoughts on the issue.
It should NOT simply just restate the title.

Issues are automatically assigned a number when created.
**Your branch should begin with this number**,
followed by a dash.
To build off the barbican example,
the feature branch should be named *13-Add-barbican-to-kinetic-framework* if the issue created was #13.

[#professional-git-usage]
== Professional Git Usage

Git can quickly become a real pain if contributors do not use it correctly.
Please read the Git Team Workflow Cheatsheet in the Introduction for a good example of standard workflow.

=== DO NOT:

* Commit directly to the master branch unless it is a very minor change (i.e fix typo, change file name, etc.)
* Have multiple significant changes take place in a single commit
** Use your best judgment on commit frequency.
A good rule of thumb is make a change,
test that change,
make sure nothing broke,
& commit.
* Submit a merge request on a feature branch that is not in sync with the master branch
** Once you believe you are complete with a feature branch,
make sure your local feature branch is rebased on top of the head of the remote master branch,
then submit your merge request.
Read the Your First Contribution section for more details.

=== DO:
* Write meaningful commit messages. More details on this can be found https://chris.beams.io/posts/git-commit/[in this blog post].
* Use the .gitignore file to ignore unnecessary files like compiled executables,
temporary files,
IDE configurations,
and other files that do not contain code or documentation.
https://www.atlassian.com/git/tutorials/saving-changes/gitignore[here is a good list] of files that should be ignored.
* Use social platforms like Slack,
GitLab,
or face-to-face meetings to discuss changes,
de-conflict pull requests,
and other work that is necessary to develop software when working as a team.

[#your-first-contribution]
== Your First Contribution

Let's walk through a simple example of how you go from an idea to a solution fully merged into the master branch.

The first step is putting the changes into words through the GitLab issue tracker.
Read the xref:contributing.adoc#submitting-issues[submitting issues] section for more information.

Once you do this,
create a new branch in GitLab by going to the repository home page,
clicking on the plus sign drop-down menu,
and selecting _New branch_.
Make sure the branch name starts with the issue number and then succinctly paraphrases the issue title.

Next, you will need to run ```git pull``` on your local machine to pull down the new branch.
Then you run ```git checkout <feature-branch-name>``` to start working in the new feature branch.

As you start making changes to your specific feature,
at some point you will determine you've reached a good point to stop,
test your changes,
make sure nothing broke,
and commit.
To do so,
first run ```git status``` to see what files have changed.
If there are files listed that you don't believe should be included in the remote repository (temporary files, local IDE configurations, compiled binaries, etc.),
add them manually to the .gitignore file.
From here you can add the files to git by running ```git add -A```.

After your files have been added,
you need to commit your changes to the feature branch.
https://chris.beams.io/posts/git-commit/[Please read this first] before you make your first commit.
A well-written commit can save a lot of time in the future when something inevitably breaks or needs to change and you want to find
the source of the problem or a good place to start over and try again.
And above all,
do not be lazy and use the ```-m``` flag unless you are fixing a simple typo or some other very minor change that doesn't warrant a description.

Once you commit your changes,
you need to make sure your changes are on top of an up-to-date version of the master branch.
To do this,
run the following commands in succession:

* ```git checkout master```
* ```git pull```
* ```git checkout -```
** the dash is a built-in git variable that represents the previous branch/commit you were working on.
In this case,
it is the name of our feature branch.
* ```git rebase master```
** Depending on what changes have been made to master since you started working on your feature,
there may be merge conflicts that you need to resolve.
An easy way to avoid this is to separate responsibilities and understand who is doing what so only one person at a time is modifying any given file.
* ```git push``` the local feature branch to the remote feature branch.

Now that your remote feature branch is based on top of an up-to-date master branch,
you can submit a merge request in GitLab.

To do this,
navigate to your branch in GitLab and click on the _Create merge request_ button.
The title should automatically be generated to say _Resolve "<issue_title>"_ and the description should say _Closes #<issue_number>_.
You should definitely add more to the description to explain how everything turned out,
what was tested,
and what to expect.

The final step before you submit the merge request is to decide if you want to delete the source branch when the merge request is accepted.
In most cases you should check the box and remove the source branch because the feature is now part of master and has no reason to continue to exist as a separate branch.

Once you verify everything,
submit the merge request.
If everything looks good by at least one other person looking over the changes and verifying that you didn't "break the build",
then it will be merged into master.

If something needs to be changed in the feature branch before merging,
then make the changes,
commit them to the feature branch,
and execute the above commands again to ensure your changes are always on top of an up-to-date master branch.
Rinse and repeat as many times as necessary.

[#gitlab-features]
== GitLab Features

GitLab has a treasure trove of features that make collaboration as painless as possible for software developers.
At a minimum,
a successful team should be using assignees,
labels,
and issues when deciding who works on what.

Assignees simply assigns a GitLab account to an issue.
You can assign multiple individuals to an issue.

Labels are useful for creating issue categories.
A simple example would be having a Feature label and a Bug label to differentiate features and bugs.
Another example specific to CCTC (for example) would be a label to differentiate between the different modules (Windows, Linux, Networking) and then a generic OpenStack label.

Issues have been explained in-depth already and should be foundational in any team workflow.

=== GitLab IDE

GitLab has a very useful web IDE that allows you to edit files directly within your browser.
Changes are tracked automatically and you can commit to either the current branch or a new branch without touching the command line.

If you are working on a system that you have not configured to your liking or you need to make changes to text documents that don't require any sort of testing,
the web IDE is a very powerful interface. For a more in-depth list of features,
read the documentation https://docs.gitlab.com/ee/user/project/repository/web_editor.html[here] and https://docs.gitlab.com/ee/user/project/web_ide/[here].
= Style Guide

Now that you know what courseware as code is,
how to register for an account,
and have a general idea of how to contribute in a meaninful manner,
its time to discuss the style with which you need to write your content so that we can quickly accept it.

IMPORTANT: You will probably notice that we don't follow our own style guide everywhere at the moment.
Don't interpret that as license to ignore it.
Our processes took awhile to catch up to our content development and we are in the process of going back and cleaning up the battlefield to bring everything in line with this style guide.

[#extensions]
== File Extensions and File Types

All contributed material that isn't source code,
supporting assets (images, etc.),
or explicitly required by a build system (e.g. .gitlab-ci.yml) *must* be in asciidoc format and end with the .adoc file extension.
This requirement covers documents,
https://asciidoctor.org/docs/asciidoctor-revealjs/[slide decks],
and more.

Word documents,
powerpoint slides,
excel spreadsheets,
and PDFs should *never* be present in the system,
unless they're a product of a https://docs.gitlab.com/ee/ci/pipelines.html[pipeline].

[#workflow]
== Workflow

As previously mentioned,
we use the https://guides.github.com/introduction/flow/[github flow] as the workflow across all Cyber School courses.
The only branch that is offical (and deployable) is master.
All other branches should be considered developmental,
not suitable for usage,
and unofficial.

When one desires to make a change to the master branch,
one should create a new https://docs.gitlab.com/ee/user/project/repository/branches/[branch],
make the necessary changes,
and do a merge request,
all in rapid succession.
Prior to doing a merge request,
one should be sure that they have https://git-scm.com/docs/git-rebase[rebased] their proposed branch against master.
Branches that are behind master make it difficult to review and approve changes,
and will be rejected.

Each feature/bugfix that someone wishes to implement should be its own branch.
Branches should never be long running,
and should be deleted as soon as they are either merged in to master or rejected by the maintainers.

When there is a particular point in the development history of the master branch that is of note (e.g. the exact commit that a course iteration starts on),
https://docs.gitlab.com/ee/university/training/topics/tags.html[tags] are to be used to keep track of it for future reference.
Using tags allows us to keep track of changes over time and correlate various changesets to differences in student outcomes,
among other things.



[#sentences]
== Sentences

When writing in asciidoc,
you *must* adhere to the https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line[one sentence per line] style.
Because asciidoc does not interpret single line breaks as actual line breaks,
you can do things like this:

[source, asciidoc]
----
The quick brown fox
jumped over
the lazy
dog
----

and have it render like this:

The quick brown fox jumped over the lazy dog.

I personally prefer to do one clause per line,
so if there is a comma or a semicolon in a sentence,
that would also trigger a line break.
That level of detail is not required for general contributions,
although certain projects may require it.

[#attributes-and-metadata]
== Attributes and Metadata

Attributes and metadata are an extremely important part of managing templatization-friendly repositories.
The Cyber School uses them to keep track of various things,
such as the various objectives covered in a particular lesson,
the objectives that a quiz question is testing,
etc.

Each project will have their own metadata and attribute requirements.
Be sure to adhere to them.
You can read more about metadata and attributes https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-attributes-i-e-variables[here]

[#pipelines]
== Pipelines

While there is currently a shell-based gitlab runner that is available and used as default for all projects,
this runner is deprecated and will be removed in the future.
It has been replaced by a docker runner,
which can be specified by using the 'docker' tag in your jobs.
All new jobs should use docker,
and all legacy jobs should be converted as soon as is practicable.
