= What is the Georgia Cyber Range?

The Georgia Cyber Range (GCR) is an implementation of the https://github.com/GeorgiaCyber/kinetic[kinetic] framework.
The kinetic framework was originally developed at the United States Army Cyber School at Fort Gordon, Georgia.

[#history]
== History

In 2015, the Army Cyber School observed that nearly all 'Cyber Range' capabilities focused on traditional x86 computing platforms;
while these platforms are important,
they are significantly less interesting than alternate architectures (ppc, arm, mips, etc.),
embedded systems,
and other technological assets that cannot be accurately captured, represented, or assessed  by traditional x86 virtualization solutions from a cybersecurity perspective.
Thus, the project that would eventually become kinetic was born.

[#components]
== What makes a traditional cyber range?

More often than not,
a Cyber Range is nothing more than a few virtual machines with freely available tools preinstalled.
There might also be static 'scenarios' that tie together a handful of virtual machines and let users apply their preinstalled tools against common malware.
The vast majority of the time,
these Cyber Ranges can be easily re-created on your home computer with virtual box and a few ansible playbooks at almost no cost.

For larger implementations,
cloud providers such as AWS, Azure, and GCE are well-suited to providing large quantities of compute, storage, and networking at the point of need in a rapid manner.
The limitations with these providers are the same as running it on your own laptop - they cannot capture the technical world beyond traditional x86 computing devices,
which is a critical requirement in our current era of technology.

[#differentiators]
== What makes the GCR Different?

The GCR leverages https://wiki.qemu.org/Documentation/Platforms[QEMU and KVM acceleration] (where applicable/available) to virtualize all kinds of traditional and non-traditional platforms,
all the way from individual binaries to entire systems.
If for some reason your platform cannot be virtualized,
the GCR fully supports Hardware-in-the-Loop (HWIL) and connecting arbtirary devices to your GCR project spaces is fast and easy.

Additionally, the GCR leverages OpenStack to provide resource scheduling and orchestration on top of the qemu/kvm hypervisor,
which lets users fully define custom, dynamic scenarios in code which can then be easily shared with others without having to tranfer large quantities of data.

Finally, because the GCR runs on the open-source kinetic framework,
you can deploy your own gcr-compatible cyber range on your own hardware at your own organization for free,
and then re-use all publicly available GCR scenarios and templates internally, and vice versa

[#supported-services]
== Supported Services

Currently, the GCR supports:

* https://docs.openstack.org/cinder/latest/[Block Storage]
* https://docs.openstack.org/nova/latest/[Compute]
* https://docs.openstack.org/zun/latest/[Containers]
* https://docs.openstack.org/designate/latest/[DNS]
* https://docs.openstack.org/keystone/latest/[Identity]
* https://docs.openstack.org/glance/latest/[Images]
* https://docs.openstack.org/neutron/latest/[Networking]
* https://docs.openstack.org/swift/latest/[Object Storage]
* https://docs.openstack.org/heat/latest/[Orchestration]
* https://docs.openstack.org/placement/latest/[Placement]

